#!/usr/bin/env python3
"""Bounded source-sliced preview: existing ScratchHead equations, shared M, matching inputs.
This is NOT a portable engine or Windows renderer. Requires .NET 9 on PATH and Pillow for PNG/GIF.
"""
from pathlib import Path
import argparse, subprocess, json, hashlib, re, os
ROOT = Path(__file__).resolve().parents[1]
BASE = '4e554f5ecc6e44701001ee56b047fd04ee82ec85'

def old(name): return subprocess.check_output(['git','show',f'{BASE}:{name}'],cwd=ROOT,text=True)
def current(name): return (ROOT/name).read_text()
def between(s,a,b):
    assert s.count(a)==1, a
    return s.split(a,1)[1].split(b,1)[0]
def case(s): return between(s,'            case Fidget.ScratchHead:\n','                break;')
def sha(s): return hashlib.sha256(s.encode()).hexdigest()
def generate():
    fig=current('Figure.cs'); pose=current('Figure.Pose.cs'); style=current('Figure.Style.cs'); fidgets=current('Figure.Fidgets.cs'); body_style=current('BodyStyle.cs')
    original=old('Figure.Style.cs')
    assert 'Fidget.ScratchHead => 1.4f' in style and 'Fidget.ScratchHead => 1.4f' in original, 'Fixture duration needs review'
    dims='        HeadR = '+between(fig,'        HeadR = ','        _gravity =')
    defaults='        float hipT = '+between(pose,'        float hipT = ','        if (Climbing)')
    # Only unused target locals are removed: this stationary fixture has no free feet.
    defaults=defaults.replace('float tiltT = 0, pdxT = 0, handW = 13, footW = 18;','float tiltT = 0, pdxT = 0, handW = 13;').replace('        Vector2 fN = default, fF = default;\n','')
    springs='        M.Spring(ref _hip,'+between(pose,'        M.Spring(ref _hip,','        if (feetFree && !_feetFree)')
    # Bind the production style read to the fixture's explicit RunStyle input; keep both spring paths.
    assert springs.count('Style.Run') == 1, 'Review the fixture style binding'
    springs=springs.replace('Style.Run', '_runStyle')
    assert springs.count('Action == Act.Cheer') == 1, 'Review the fixture action binding'
    springs=springs.replace('Action == Act.Cheer', '_isCheer')
    run_style='enum RunStyle '+between(body_style,'enum RunStyle ','\n')+'\n'
    flail_spring='    void SpringFlailHand('+between(pose,'    void SpringFlailHand(','    Vector2 SwatDir()')
    geometry='        Vector2 pelvis = '+between(pose,'        Vector2 pelvis = ','        Vector2 footN, footF;')
    assert geometry.count('Action == Act.Cheer') == 1 and geometry.count('Style.Celebrate == CelebrateStyle.Flex') == 1, 'Review the fixture Flex bindings'
    geometry=geometry.replace('Action == Act.Cheer', '_isCheer').replace('Style.Celebrate == CelebrateStyle.Flex', '_isFlex')
    knees='        var (knN, fNEnd) = '+between(pose,'        var (knN, fNEnd) = ','        UpdateHoldPoint(')
    joints='static class J\n{'+between(fig,'static class J\n{','\n}')+'\n}'
    envelope='static float Envelope'+between(fidgets,'static float Envelope','\n')
    generated='''// Generated by tools/visual-preview.py. Do not edit. See source-manifest.json.
using System.Numerics;
namespace Doodlefolk;
'''+joints+run_style+'''
static class SourceSlices
{
'''+envelope+'''
public static void Scratch(bool before, float t, float dur, float S, float HeadR, float NeckGap, float Arm, int Facing, Vector2 _hN, ref Vector2 hN, ref Vector2 eN, ref float tiltT, ref float handW)
{
float p=M.Clamp01(t/MathF.Max(dur,.1f)); float env=Envelope(p);
if (before)
{
'''+case(original)+'''
}
else
{
'''+case(style)+'''
}
}
}
sealed partial class PoseFixture
{
'''+flail_spring+'''
void Dimensions()
{
'''+dims+'''
}
public (Vector2 hand, Vector2 elbow, float tilt, Vector2 rest) Target(float t)
{
float br=0;
'''+defaults+'''
Vector2 rest=hN;
SourceSlices.Scratch(_before,t,1.4f,S,HeadR,NeckGap,Arm,Facing,_hN,ref hN,ref eN,ref tiltT,ref handW);
// Read unused defaults so warnings-as-errors can stay enabled for this source-derived block.
_ = hipT + hipW + hipZ + leanT + leanW + pdxT; _ = hF + eF + kPref;
return (hN,eN,tiltT,rest);
}
public void Step(float dt,float time,bool active)
{
_time=time;
float br=MathF.Sin(_time*2.3f+Id);
'''+defaults+'''
if (active) SourceSlices.Scratch(_before,time-.4f,1.4f,S,HeadR,NeckGap,Arm,Facing,_hN,ref hN,ref eN,ref tiltT,ref handW);
'''+springs+'''
float hip=_hip,bob=0;
// Figure.Pose's reach limit with stationary feet; no step bob (neither foot stepping).
float dx=MathF.Max(MathF.Abs(5.5f*S-_pdx),MathF.Abs(-5.5f*S-_pdx));
float reach=MathF.Sqrt(MathF.Max(0,Leg*Leg*.97f-dx*dx));
if (reach<hip) hip=MathF.Max(reach,MathF.Min(hip,StandHip*.88f));
'''+geometry+'''
Vector2 footN=new(Base.X+Facing*5.5f*S,Base.Y),footF=new(Base.X-Facing*5.5f*S,Base.Y);
'''+knees+'''
}
}
'''
    dest=ROOT/'tests/Doodlefolk.VisualPreview/obj';dest.mkdir(parents=True,exist_ok=True)
    (dest/'SourceSlices.g.cs').write_text(generated)
    manifest={'baselineCommit':BASE,'scope':'stationary ScratchHead only; fixed neutral before/after; no world, foot planner, adornments or Windows renderer','baselineFidgetCase':case(original),'candidateFidgetCase':case(style),'inputs':{'scale':1,'facing':1,'identity':1,'runStyle':'Sprinter','start':.4,'fidgetDuration':1.4,'totalSeconds':2.8,'simulationHz':120,'outputFps':30},'fixtureBindings':{'Style.Run':'_runStyle (explicit fixture input; production spring branches and helper retained)'},'currentSourceSHA256':{p:sha(current(p)) for p in ['Figure.cs','Figure.Style.cs','Figure.Fidgets.cs','Figure.Pose.cs','Figure.Draw.cs','BodyStyle.cs','Util.cs']},'generatedSHA256':sha(generated)}
    (dest/'source-manifest.json').write_text(json.dumps(manifest,indent=2))
    print('Generated exact before/after ScratchHead source slices and current production spring/IK fixture')
    return manifest

if __name__=='__main__':
    ap=argparse.ArgumentParser();ap.add_argument('--generate',action='store_true');ap.add_argument('--output',type=Path);a=ap.parse_args();generate()
    if a.output:
        a.output.mkdir(parents=True,exist_ok=True)
        subprocess.run(['dotnet','run','--project',str(ROOT/'tests/Doodlefolk.VisualPreview'),'-c','Release','--',str(a.output/'scratchhead-poses.json')],check=True,cwd=ROOT,env={**os.environ,'DOTNET_TieredCompilation':'0'})
        import shutil
        shutil.copy(ROOT/'tests/Doodlefolk.VisualPreview/obj/source-manifest.json',a.output/'source-manifest.json')
